# Generated by Django 3.2.6 on 2021-10-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('payments', models.TextField(blank=True, null=True)),
                ('sum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HISTORY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TodayProc',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('all_sum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'today_proc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(blank=True, null=True)),
                ('address_wallet', models.TextField(blank=True, null=True)),
                ('balance_invest', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('first_referal', models.IntegerField(blank=True, null=True)),
                ('second_referal', models.IntegerField(blank=True, null=True)),
                ('three_referal', models.IntegerField(blank=True, null=True)),
                ('four_referal', models.IntegerField(blank=True, null=True)),
                ('five_referal', models.IntegerField(blank=True, null=True)),
                ('progres', models.IntegerField(blank=True, null=True)),
                ('laung', models.TextField(blank=True, null=True)),
                ('address_btc', models.TextField(blank=True, null=True)),
                ('address_eth', models.TextField(blank=True, null=True)),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'USER',
                'verbose_name_plural': 'USERS',
                'db_table': 'USER',
                'managed': False,
            },
        ),
    ]
